### PR TITLE
Fix $BASEDOMAIN variable name

### PR DESCRIPTION
**Pull request by daniele-athome**
Signed-off-by: Daniele Ricci daniele.athome@gmail.com

### CODE REVIEW

**Comment by battlesnake** [comment]
Thanks, I wasn't aware that anyone else used my projects!

**Comment by daniele-athome** [comment]
In fact I'm using it for my own home server :-) thanks!

**Comment by battlesnake** [comment]
Wow, someone who can actually understand my crappy documentation!

There's a much nicer and less hacky DDNS interface that I've coded in Node.js, I'll put that up on github whenever I next return home!

**Comment by battlesnake** [comment]
I originally designed this DDNS to be used in conjunction with MACS [ https://github.com/battlesnake/macs ].

I have a Raspberry Pi running a DDNS client (which CURLs the DDNS server's "update IP" command periodically).  The DDNS server runs on a VPS at DigitalOcean.  On the Pi, I also run MACS, which periodically scans the local network and keeps a database of hostnames, IP addresses and MAC addresses.

This allows me to leave my power-hungry home server in S3 standby (very low power usage) when I'm not using the server.  To access it, I simply use the MACS web interface to send a Wake-On-Lan command to the server, which causes it to power up.  The server shares the same IP as my Raspberry Pi, as they are both behind a router - so the DDNS address for the Pi also gives access to the home server, e.g: if the Pi web interfaces are at home.mydomain:8080 then I simply use home.mydomain:22 for SSH to the server instead.  This is one extremely rare case of NAT and firewalls actually making life easier for people...

**Comment by daniele-athome** [comment]
Seems like I too could use this idea of the wake on LAN and dedicated board
to update the DNS. Nice :-)

Daniele

**Comment by battlesnake** [comment]
If you have any trouble setting it up, let me know!  Likewise, feel free to submit patches or improve the documentation!  The MACS software has also been ported to Node.js, and is part of a suite including the DDNS and other stuff... I'll put all that up on github if I ever stop travelling!

**Pull request merged**
